### ISSUE TITLE
Not working with Certbot v0.33.1?

### ISSUE THREAD

**Issue by siccovansas** [hsmade/certbot-dns-transip#11]
I updated to Certbot v0.33.1 and got the following error when I did a dry run:

```
Cleaning up challenges
Encountered exception during recovery: 
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/error_handler.py", line 124, in _call_registered
    self.funcs[-1]()
  File "/opt/certbot/src/certbot/auth_handler.py", line 220, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/opt/certbot/src/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_transip/dns_transip.py", line 71, in _cleanup
    self._get_transip_client().del_txt_record(domain, validation_name, validation)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_transip/dns_transip.py", line 159, in del_txt_record
    domain_records = self._get_dns_entries(domain_name=domain)
TypeError: _get_dns_entries() got an unexpected keyword argument 'domain_name'
Attempting to renew cert (subsidietrekker.nl) from /etc/letsencrypt/renewal/subsidietrekker.nl.conf produced an unexpected error: '_TransipClient' object has no attribute 'get_dns_entries'. Skipping.
```

I didn't dive into the problem, but when I downgrade back to v0.31.0 the error doesn't occur any more. Any ideas?

**Comment by hsmade** [comment]
Hai!

Could you try to reproduce the problem, and when you do, post the output of `pip freeze` ?

**Comment by siccovansas** [comment]
Sure, this is the output of `pip freeze` when I get the problem:

```
# Editable install with no version control (acme==0.33.1)
-e /opt/certbot/src/acme
asn1crypto==0.24.0
# Editable install with no version control (certbot==0.33.1)
-e /opt/certbot/src
certbot-dns-transip==0.2.0
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
ConfigArgParse==0.14.0
configobj==5.0.6
cryptography==2.6.1
enum34==1.1.6
funcsigs==1.0.2
future==0.17.1
idna==2.8
ipaddress==1.0.22
josepy==1.1.0
mock==1.3.0
parsedatetime==2.4
pbr==5.1.3
pyasn1==0.4.5
pycparser==2.19
pyOpenSSL==19.0.0
pyparsing==2.3.1
pyRFC3339==1.1
python-augeas==0.5.0
pytz==2018.9
requests==2.21.0
requests-toolbelt==0.9.1
rsa==4.0
six==1.12.0
suds-jurko==0.6
transip==0.4.0
urllib3==1.24.1
zope.component==4.5
zope.deferredimport==4.3
zope.deprecation==4.4.0
zope.event==4.4
zope.hookable==4.2.0
zope.interface==4.6.0
zope.proxy==4.3.1
```

[This is the Dockerfile](https://github.com/openstate/nginx-load-balancer/blob/master/docker/Dockerfile-certbot) which I use for certbot and certbot-dns-transip.

**Comment by ActuallyRuben** [comment]
I just came across the same issue, I found two problematic lines:

https://github.com/hsmade/certbot-dns-transip/blob/4a8c1d719c221fe38bb0116004c9ee44d7577b3f/certbot_dns_transip/dns_transip.py#L117
`get_dns_entries` doesn't exist, it should be `_get_dns_entries`

https://github.com/hsmade/certbot-dns-transip/blob/4a8c1d719c221fe38bb0116004c9ee44d7577b3f/certbot_dns_transip/dns_transip.py#L159
`domain_name` isn't a valid keyword argument, and shouldn't be used for this function

I'm posting a pull request in a minute to fix this.

**Comment by ActuallyRuben** [comment]
PR #12 should fix it.

**Comment by hsmade** [comment]
Merged, pushing a new version now.
Thx!

**Comment by siccovansas** [comment]
Thanks for the quick actions!

I tried version 0.2.3, but got a new error :)

```
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/error_handler.py", line 124, in _call_registered
    self.funcs[-1]()
  File "/opt/certbot/src/certbot/auth_handler.py", line 220, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/opt/certbot/src/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_transip/dns_transip.py", line 71, in _cleanup
    self._get_transip_client().del_txt_record(domain, validation_name, validation)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_transip/dns_transip.py", line 159, in del_txt_record
    domain_records = self._get_dns_entries(domain)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_transip/dns_transip.py", line 192, in _get_dns_entries
    dns_entries = _get_dns_entries_transip(domain)
TypeError: _get_dns_entries_transip() takes exactly 2 arguments (1 given)
Attempting to renew cert (openstate.eu) from /etc/letsencrypt/renewal/openstate.eu.conf produced an unexpected error: _get_dns_entries_transip() takes exactly 2 arguments (1 given). Skipping.
```

**Comment by hsmade** [comment]
Ok, ok.. *fires up IDE*

**Comment by ActuallyRuben** [comment]
Whelp, guess I should've tested my fix. But I never learn, so here is another untested PR that should fix things: #13

**Comment by hsmade** [comment]
BTW, I'm not using this software anymore myself. I use [lego](https://github.com/go-acme/lego) and/or [traefik](https://traefik.io)

**Comment by hsmade** [comment]
0.2.4 is going through the pipeline now

**Comment by siccovansas** [comment]
0.2.4 works like a charm, thanks @hsmade and @ActuallyRuben!
